### ISSUE TITLE
See if we can fix the end-of-tx clock tail

### ISSUE THREAD

**Issue by vk3il** [camilstaps/SODA-POP-source#12]
As per issue raised on AT-Sprint where clock takes a bit of time to shut off after returning to RX mode and hence making QSK very difficult.

**Comment by camilstaps** [comment]
We now switch directly back to RX mode after each dot and dash. Fortunately, this does not seem to cause any 'plopping' sounds.

**Comment by camilstaps** [comment]
QSK is still difficult, because the sidetone affects the AGC.
