### ISSUE TITLE
Bug in fetch_callibration_data()?

### ISSUE THREAD

**Issue by vk3il** [camilstaps/SODA-POP-source#23]
Looking at the start of this function:

void fetch_calibration_data()
{
  unsigned long temp = 0;

  temp = EEPROM.read(3);
  IFfreq = IFfreq+temp;

I think the first assignment of IFfreq should be just IFfreq = temp; 
Otherwise, you are relying on IFfreq being zero on power up (which it would likely be). Or am I misunderstanding this?

**Comment by camilstaps** [comment]
You are right. It did not cause any problems, because the function only gets called when `IFfreq = 0`. But it didn't look so neat. I think I overlooked it when I rewrote the code.
