### ISSUE TITLE
IFfreq display during calibration

### ISSUE THREAD

**Issue by vk3il** [camilstaps/SODA-POP-source#24]
At present the code displays P. IF in the calibration routine whereas the original code displayed the actual IF frequency. I think it would be preferable to go back to displaying the IF frequency as this is hard to measure (no accessible test point for this on the top side of the board). Having the IF freq displayed is a cross check that you haven't tuned way outside the filter band. 

In fact, it may be helpful to actually flash the display if you move too far above or below the filter bandwidth as I suspect this is the cause of a number of people's low sensitivity problems.

I would suggest displaying the 10's of Hz digit as the lowest one and drop the 100's kHz digit to help locate yourself in the tuning range.

**Comment by camilstaps** [comment]
Good idea. I changed this initially to make the different steps in the calibration routine distinct, but that is of course also possible when you show the IF frequency.
