### ISSUE TITLE
Beacon mode

### ISSUE THREAD

**Issue by camilstaps** [camilstaps/SODA-POP-source#6]
As Razvan, DL2ARL, [suggested](https://groups.yahoo.com/neo/groups/AT_Sprint/conversations/messages/17717), it would be nice to bring back beacon mode.

**Comment by vk3il** [comment]
Agree. If possible, allow any memory to be set to beacon. Use case I am thinking about is a SOTA activation where I do several summits in one day and want to pre-store a CQ including the summit details before I head out.

**Comment by camilstaps** [comment]
You can now turn on and off beacon mode during the transmission of any message, as you suggested, using the keyer switch. The display changes from `Snd` to `bcn`. The interval between beacon transmissions can be set as a number of dot-times in `settings.h` (`BEACON_INTERVAL`).

It is now also possible to end any active transmission by pressing the RIT switch.

Both changes are documented in the readme.
