### ISSUE TITLE
Add #defines for all user configurable parameters

### ISSUE THREAD

**Issue by vk3il** [camilstaps/SODA-POP-source#7]
I think it would be helpful to create a section of #defines near the start of the code to allow users to compile in a range of defaults that suit them. I'm thinking particularly codes speed and all the band limits/default operating frequencies. The current set are not suitable for VK for example.

**Comment by camilstaps** [comment]
Apart from #14 I think this is all done now.

**Comment by vk3il** [comment]
#14 now complete
